spring:
    application:
        name: recommend-content-service

    config:
        import: configserver:http://localhost:10500

    cloud:
        config:
            fail-fast: true

server:
    error:
        include-message: always
        include-stacktrace: always
        include-exception: true