spring:
    application:
        name: recommend-content-service

    config:
        import: configserver:http://localhost:10500

    cloud:
        config:
            fail-fast: true

    jpa:
        open-in-view: false          # 트랜잭션 범위 밖에서 DB 연결 유지 X (성능 최적화 필수)
        show-sql: true               # 실행되는 쿼리 로그 출력
        hibernate:
            ddl-auto: update           # update: 스키마 자동 변경 (운영에선 none 또는 validate 추천)

server:
    error:
        include-message: always
        include-stacktrace: always
        include-exception: true
        